"""empty message

Revision ID: 36c8971a65da
Revises: 
Create Date: 2017-11-14 10:24:39.098695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36c8971a65da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('game', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.add_column('player', sa.Column('player_name', sa.String(length=16), nullable=True))
    op.alter_column('player', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player_answers', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player_answers', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('question', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('question', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('question', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player_answers', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player_answers', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('player', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.drop_column('player', 'player_name')
    op.alter_column('game', 'updated_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    op.alter_column('game', 'created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    # ### end Alembic commands ###
